<?php
$title = 'Deletar álbum';

$this->headTitle($title);
$url = $this->url('album', ['action' => 'delete', 'id' => $id]);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<form action="<?php echo $url ?>" method="post">
    <p>Você tem certeza que deseja deletar este álbum?</p>
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo $album->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-default" name="del" value="Não" />
    </div>
</form>