<?php
$title = 'Editar álbum';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php 
$form->setAttribute('action', $this->url('album', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
<label for="artist">Nome do Artista</label>
<?php
echo $this->formRow($form->get('artist'));
?>
</div>
<div class="form-group">
<label for="title">Título</label>
<?php
echo $this->formRow($form->get('title'));
?>
</div>
<button onclick="location.href = '<?= $this->url('album') ?>';" class="btn btn-default">Voltar</button>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>